### PR TITLE
Problem with islets

### PR DESCRIPTION
**Pull request by iwbh15**
I run into a problem when stitching a slide consisting of or degrading into a set of islets.
I would like to discuss the solution I have worked out?
Peter

### CODE REVIEW

**Comment by iwbh15** [comment]
After updating my code today I would like to describe the problem and the solution more in detail.

When a set of images from a large specimen consist of several unconnected collections of connected images this unconnected collections (islets) will all be placed over each other during global optimization.
The reason is that the Stitching plugin reset the original coordinate system of the tiles and uses a coordinate system with an origin at the centre of each of the unconnected islets. The islets will then be placed over each other at their coordinate origin.
In my solution I detect the different islets, optimize the collections separately and reassign the coordinates of the original coordinate system.

This seems to be important for scans where islets are created due to a rejection of tiles based on the correlation threshold as well as for scans where different unconnected islets are captured at different location on the slide.

I appreciate any feedback.

**Comment by StephanPreibisch** [comment]
Sorry, I missed the original post ... checking it out now

**Comment by iwbh15** [comment]
There is one more issue. So, my solution is still not perfect.
During optimization of the islets (collection of connected images) images can be rejected due to a huge displacement. This images are incorrectly placed in the final image.
Cuurently I simply reject those images from the collection when the a huge displacement is detected. But this is just a workaround.
Any idea for a better improvement?

**Comment by ctrueden** [comment]
@StephanPreibisch @iwbh15 Any updates on the status of this PR? Should we close it?

If not, I personally would like to see clean commits with good messages, as per the [ImageJ coding style guidelines](http://imagej.net/Coding_style#SCM_history). As is, it is very hard to review.

**Comment by iwbh15** [comment]
Sorry for this old PR still open.
Worls has changed - for sure.
I close this PR.

**Pull request closed without merging**
